<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Title' => 'Название',
	'Slug' => 'Алиас',
	'Description' => 'Описание',
	'Created At' => 'Создано',
	'Updated At' => 'Обновлено',
	'Status' => 'Статус',
	'Intro' => 'Вступительный текст',
	'Published At' => 'Показать с даты',
	'Created By' => 'Автор',
	'Article' => 'Материал',
	'Parent' => 'Родитель',
	'Comment' => 'Комментарий',
	'User Name' => 'Логин',
	'Name' => 'Имя',
	'Email' => 'E-mail',
	'Not Published' => 'Скрыто',
	'Published' => 'Показано',
	'Categories' => 'Категоии',
	'Select category' => 'Укажите категоии',
	'Image' => 'Изображение',
	'Save' => 'Сохранить',
	'Category' => 'Категория',
	'Categories' => 'Категории',
	'Articles' => 'Материалы',
	'Menu' => 'Меню',
	'Settings' => 'Настройки',
	'Administrative area' => 'Администрирование',
	'Updating: {nameAttribute}' => 'Обновление: {nameAttribute}',
	'Update' => 'Обновление',
	'Route' => 'Маршрут',
	'Link' => 'Ссылка',
	'Select type' => 'Выберите тип',
	'Url' => 'Ссылка',
	'Type' => 'Тип',
	'Delete' => 'Удалить',
	'Key' => 'Ключ',
	'Data' => 'Значение',
	'Key can only contain alphanumeric characters, point and dashes.' => 'Ключ может содержать только буквенно-цифровые символы, точки и тире',
	'Logout' => 'Выход'
];
